### PR TITLE
Fix most PSSA warnings - suppressed a few.

### PR DESCRIPTION
**Pull request by rkeithhill**
Fix PS ScriptAnalyzer warnings. There should be zero warnings now.

Also normalized casing on $env:path to $env:PATH because on *nix systems env var is upper case.

## Motivation and Context

Broken window theory - if we have too many PSSA warnings they will just be ignored.  By getting to zero it becomes more obvious when new warnings are introduced.

## How Has This Been Tested?

Ran all the Pester tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Infrastructure improvement.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by devblackops** [comment]
re: the doc tests. These are bugging me too 😄 

I'm wondering if we need to do such a specific comparison between the doc strings. Would just comparing the string length be enough to satisfy the test? It would be pretty unlikely that the string length is the same yet psake returns unexpected text. Just a thought.

**Comment by rkeithhill** [comment]
Call me Ahab now and those doc tests are the "white whale".  :-)  Give me a bit more time to see if I can figure it out.  BTW, we are slamming EOL to CRLF in .gitattributes.  For anybody that would care to clone and develop on Linux/Mac, this isn't ideal.  Seems to me we should set text to auto in general so that on Linux/Mac folks get LF for EOL which should work better for their editors.  Thoughts?

**Comment by rkeithhill** [comment]
OK, docs tests pass and that's all the Linux build need.  There are a couple of failures on OSX around `default_buildfile` tests. Will look into those next.

**Comment by devblackops** [comment]
I'm OK with changing .gitattributes. Maybe also set `files.eol": "\n"` in the `settings.json`?

**Comment by rkeithhill** [comment]
I don't think we need to change settings.json.  For Windows users, the files will be CRLF EOL and VSCode will handle that just fine on Windows.  On Linux/Mac, the files will be LF EOL and again, VSCode should handle that just fine.  BTW there is .gitattributes setting that makes markdown file merges easier.  We might want to set that - see https://github.com/PowerShell/PowerShell/blob/master/.gitattributes

**Comment by devblackops** [comment]
It's happening! https://media.giphy.com/media/rl0FOxdz7CcxO/giphy.gif

**Comment by rkeithhill** [comment]
Drops the mike!  Oh yeah.  Now to clean up and squash some commits.

**Pull request merged**
