### PR TITLE
Refactor Task for PascalCase

### PR DESCRIPTION
**Pull request by Splaxi**
Convert parameter names into pascal

## Description

Convert parameter names into pascal
## Related Issue
#308 

## How Has This Been Tested?

```
ps>Get-Help Task -Full

NAME
    Task

SYNOPSIS
    Defines a build task to be executed by psake


SYNTAX
    Task [-Name] <String> [[-Action] <ScriptBlock>] [[-PreAction] <ScriptBlock>] [[-PostAction] <ScriptBlock>]
    [[-PreCondition] <ScriptBlock>] [[-PostCondition] <ScriptBlock>] [[-ContinueOnError]] [[-Depends] <String[]>]
    [[-RequiredVariables] <String[]>] [[-Description] <String>] [[-Alias] <String>] [<CommonParameters>]

    Task [-Name] <String> [[-Action] <ScriptBlock>] [[-PreAction] <ScriptBlock>] [[-PostAction] <ScriptBlock>]
    [[-PreCondition] <ScriptBlock>] [[-PostCondition] <ScriptBlock>] [[-ContinueOnError]] [[-Depends] <String[]>]
    [[-RequiredVariables] <String[]>] [[-Description] <String>] [[-Alias] <String>] [-FromModule] <String>
    [[-RequiredVersion] <String>] [[-MinimumVersion] <String>] [[-MaximumVersion] <String>] [[-LessThanVersion]
    <String>] [<CommonParameters>]


DESCRIPTION
    This function creates a 'task' object that will be used by the psake engine to execute a build task.
    Note: There must be at least one task called 'default' in the build script


RELATED LINKS
    Assert
    Exec
    FormatTaskName
    Framework
    Get-PSakeScriptTasks
    Include
    Invoke-psake
    Properties
    TaskSetup
    TaskTearDown

REMARKS
    To see the examples, type: "get-help Task -examples".
    For more information, type: "get-help Task -detailed".
    For technical information, type: "get-help Task -full".
    For online help, type: "get-help Task -online"
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Splaxi** [comment]
I was hoping that you had some kind of build task, that would auto populate the markdown files of the project 🤞

**Comment by Splaxi** [comment]
Found the `CreateMarkdownHelp` in the `build.ps1` file

**Review by devblackops — APPROVED** [review]

**Comment by devblackops** [comment]
Thanks @Splaxi.

**Comment by Splaxi** [comment]
@devblackops Do you want me to take a swing at the other cmdlets / functions while I'm at it?

**Comment by devblackops** [comment]
@Splaxi That'd be great. Thanks.

**Pull request merged**
