### PR TITLE
Using ErrorAction Ignore in PSv3+

### LINKED ISSUE #126: Cannot find the Windows PowerShell data file 'psake.psd1'
When I run my [build script](https://github.com/ewilde/crane/blob/develop/build.ps1) on TeamCity I get the following error
```
System.Management.Automation.PSInvalidOperationException: Cannot find the Windows PowerShell data file 'psake.psd1' in directory 'C:\TeamCity\buildAgent\work\824ebd4bb7c8f4ec\build\en-US\', or in any parent culture directories.
```

However if I run the script locally in a normal powershell window the `$Error` variable is not polluted. I noticed that this was report in issue #19, not sure what i'm doing wrong

### PR DESCRIPTION
**Pull request by dlwyatt**
Should fix #126 .

### CODE REVIEW

**Comment by gep13** [comment]
:+1:

**Comment by gep13** [comment]
@dlwyatt were you planning on hitting any of the other issues that are outstanding, or do you want to go ahead and push out this change as a new version?

**Comment by dlwyatt** [comment]
It's always okay to push out a new release.  :)

I think I'll work on #145 at some point soon, but may need to beef up the test suite a bit first.

**Comment by gep13** [comment]
Okay, since I am working on this just now, I think I will push out 4.6.0, and then the others can follow, as and when.

I have just pushed out the latest version of psake-contrib, now that I have been given ownership of the package on NuGet :smile:

**Pull request merged**
