### PR TITLE
adding support for .NET 4.6.1

### PR DESCRIPTION
**Pull request by jdaigle**

### CODE REVIEW

**Comment by gep13** [comment]
Thanks for your contribution!  I will get this pulled into a release over the next couple days.  Just waiting for the permissions needed to push the package to nuget.org and chocolatey.org.  Thanks!

**Comment by damianh** [comment]
+1

**Comment by gep13** [comment]
@damianh I am good to push this tonight, but I am still considered about the failing test that I am seeing.  Any thoughts on why this is failing for me.  Is this environment specific do you think?

**Comment by damianh** [comment]
sorry lad no clue

**Comment by damianh** [comment]
push it anyway

**Comment by nightroman** [comment]
````
Assert ($output -NotLike "14.0") '$output should contain 14.0'
````
Should it be `-like`?

**Pull request merged**
