### PR TITLE
Spelling fixes in docs and script comments

### PR DESCRIPTION
**Pull request by alexandear**
- PowerShell
- Internet
- Google
- FAQ
- command
- overridden
- override
- isn't

### CODE REVIEW

**Comment by alexandear** [comment]
@gep13 anybody here?

**Comment by damianh** [comment]
Looks safe enough; thanks for PR.

**Comment by gep13** [comment]
@alexandear sorry, this one must have got lost in my email 😢 

@damianh thanks for merging this!

**Comment by damianh** [comment]
No worries, it happens ;)

**Pull request merged**
