### PR TITLE
Added an option '-notr' to disable output of time report.

### PR DESCRIPTION
**Pull request by svgorbunov**
P.S.: My editor removes white space at the end of lines in the file `en-US\psake.psm1-help.xml`

### CODE REVIEW

**Comment by gep13** [comment]
@dlwyatt what are  your thoughts on this?

It looks good to me :+1:

**Comment by dlwyatt** [comment]
I don't really have an opinion on whether a new switch should be added to the command (API change).  If you think it's valuable, then the implementation looks fine to me.

**Comment by gep13** [comment]
@dlwyatt since it is a non mandatory, additive change, I don't see any reason to not accept it :smile:

**Comment by gep13** [comment]
@svgorbunov thank you for your contribution to psake!

**Comment by svgorbunov** [comment]
You’re welcome :) I hope, I can contribute more.

P.S.: Sorry, if my English is bad. I use Google Translate :(

**Comment by gep13** [comment]
>@svgorbunov said...
P.S.: Sorry, if my English is bad. I use Google Translate :(

I had no issues in understanding you, so you are doing perfectly well :+1:

**Pull request merged**
