### PR TITLE
Ensuring postAction and tearDown gets called on Action failure

### PR DESCRIPTION
**Pull request by stephan-dowding**
A quick patch to fix a little bug bear of mine...
I normally expect things like `PostAction` and `TearDown` to be called even if the main `Action` has failed.  This is because it is natural for me to use things like `PreAction` and `SetUp` to reserve resources and setup the environment for the `Action`.  I will then use `PostAction` and `TearDown` to release those resources and wind down the environment.  Having all that stuff hanging around after a test failure was extremely annoying!
I know I could have used `try`...`finally` within my `Action` blocks, but these constructs felt like the natural and intended place for them, hence the pull request!

### CODE REVIEW

**Comment by stephan-dowding** [comment]
Sorry for the delay!!
I've added a couple of specs, but I can't really see a way to make them more convincing without overhauling the spec library.

**Comment by colin-sim** [comment]
Is there an update on this pull request? I would very much like this functionality also.

**Comment by devblackops** [comment]
@stephan-dowding This looks good to me but given the age of this, there are some conflicts with the existing PR. I'm going to create a new one and include your changes.

**Comment by devblackops** [comment]
Creating new PR #227 which is up to date with psake. Closing this one out. Thanks @stephan-dowding!

**Pull request closed without merging**
