### PR TITLE
Project structure refactor

### PR DESCRIPTION
**Pull request by devblackops**
Big project refactor here but should not see any externally facing behavior.

## Summary of changes
* Refactored module to use one file per function.
* Moved to comment-based help instead of MAML and generated MD files using [PlatyPS](https://github.com/PowerShell/platyPS). This should make it easier to keep the help up to date and to include MD files in the [RTD](http://psake.readthedocs.io/en/latest/) site.
* Updated nuget.exe to 4.3.0.4406.
* Added chocolateyUninstall.ps1 script to Chocolatey package.
* Update Linux/macOS tests to use PowerShell 6.0.0-rc and new pwsh executable name. [#4214](https://github.com/PowerShell/PowerShell/issues/4214)
* Added VSCode tasks.
* Updated build.ps1 to include common build tasks (PSScriptAnalyzer, Pester, BuildNuget) for the project and a basic implementation of task dependencies. Borrowed from @jaykul's [gist](https://gist.github.com/Jaykul/e0c08be051bed56d62474ae12b9b1b8a). Not ready for psake tasks to manage psake just yet 😏 

## Related Issue
#226 
#225 
#197 

## How Has This Been Tested?
Manually ran test suite on Windows 10 and macOS with no issues. **AppVeyor tests pass but oddly the Travis ones do not. This will have to be tracked down.**

@PowerSchill, you added the Travis tests initially, maybe you can take a peek and see if I messed something up?

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rkeithhill** [comment]
I would recommend a tasks.json like this which is very similar to what we use on the PowerShell extension for VSCode.
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",

    "windows": {
        "options": {
            "shell": {
                "executable": "powershell.exe",
                "args": [ "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command" ]
            }
        }
    },
    "linux": {
        "options": {
            "shell": {
                "executable": "/usr/bin/pwsh",
                "args": [ "-NoProfile", "-Command" ]
            }
        }
    },
    "osx": {
        "options": {
            "shell": {
                "executable": "/usr/local/bin/pwsh",
                "args": [ "-NoProfile", "-Command" ]
            }
        }
    },

    "tasks": [
        {
            "label": "CreateMarkdownHelp",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task CreateMarkdownHelp -Verbose"
        },
        {
            "label": "PublishPSGallery",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task PublishPSGallery -Verbose"
        },
        {
            "label": "PublishChocolatey",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task PublishChocolatey -Verbose"
        },
        {
            "label": "Test",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task Test -Verbose",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "problemMatcher": "$pester"
        },
        {
            "label": "BuildNuget",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task BuildNuget -Verbose"
        },
        {
            "label": "Analyze",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task Analyze -Verbose"
        },
        {
            "label": "Pester",
            "type": "shell",
            "command": "${cwd}/build.ps1 -Task Pester -Verbose",
            "problemMatcher": "$pester"
        }
    ]
}
```
This eliminates a number of warnings about the deprecated fields: `suppressTaskName` and `taskName`.

**Comment by devblackops** [comment]
Thanks @rkeithhill. I'll make those changes.

**Comment by rkeithhill** [comment]
A couple of other suggestions.  I wonder if we could put the `nuget` folder (and NugetPackageBuilder.ps1) under `build` since these are artifacts required to build the nuget pkg.  I like Joel's approach of putting the source under a folder called `src`.  To make this repo easier to import, you create a build task that copies the appropriate files into a folder under the repo root named with the upcoming version number e.g. `psake\4.7.0`.  This also helps with getting the generated help files put into place and if you authenticode sign the files, you can sign them in this output folder and not have to touch the original source files.  

Given that, there should be a `build` task in build.ps1 and a corresponding `build` task in tasks.json that has the following setting:
```
            "group": {
                "kind": "build",
                "isDefault": true
            },
```
This will allow you to kick off a build with <kbd>Ctrl+Shift+B</kbd>.

Also, psake.ps1, psake-config.ps1 and psake.cmd are source files and should go under `src`. I don't think we need to ship the README.md, do you?  I think we'd be far better off with an `about_psake.help.txt` file to provide an overview of psake that would be accessible from the PowerShell help system.  I don't think that exists yet so maybe we create that for a future release (don't need to hold this one up for that).

Sorry, probably more feedback than you wanted.  :-)

**Comment by rkeithhill** [comment]
RE this:
```
25:131ms> Invoke-psake -task test
psake version 4.6.0
Copyright (c) 2010-2014 James Kovacs & Contributors

Error: 11/20/2017 9:59:13 PM:
 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Assert: Could not find the build file psakefile.ps1.
```
Should we rename the build.ps1 to psakefile.ps1??

**Comment by rkeithhill** [comment]
I'm getting this error when I try to import the module in my WSL console:
```
/mnt/c/Users/Keith/GitHub/psake/psake/psake [project-layout ≡ +0 ~1 -0 !]
> ipmo ./psake.ps
psake.psd1  psake.psm1
> ipmo ./psake.psd1
LoadConfiguration : The term 'LoadConfiguration' is not recognized as the name of a cmdlet, function, script file, or
operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At /mnt/c/Users/Keith/GitHub/psake/psake/psake/psake.psm1:100 char:1
+ LoadConfiguration
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (LoadConfiguration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by devblackops** [comment]
`build.ps1` isn't a psake script so `invoke-psake` won't work on it. Just run `.\build.ps1 -task test`

**Comment by rkeithhill** [comment]
Yeah, I guess if build.ps1 were a psake file you'd need a older version to bootstrap the build of psake. :-)

**Comment by devblackops** [comment]
>The term 'LoadConfiguration' is not recognized as the name of a cmdlet, function, script file, or
operable program.

Interesting. That is the same error that Travis spits out. https://travis-ci.org/psake/psake/jobs/305103591#L531

On my personal mac the tests clean. In the travis macOS build, Pester runs but fails on a few. Something is afoot.

**Comment by devblackops** [comment]
>Yeah, I guess if build.ps1 were a psake file you'd need a older version to bootstrap the build of psake. :-)

I wasn't ready to go that meta yet. 😄

**Comment by rkeithhill** [comment]
Ah, case-sensitivity on Linux is biting us.  These two lines in psm1 should be:
```
$public = @(Get-ChildItem -Path (Join-Path -Path $PSScriptRoot -ChildPath 'public/*.ps1') -Recurse -ErrorAction Stop)
$private = @(Get-ChildItem -Path (Join-Path -Path $PSScriptRoot -ChildPath 'private/*.ps1') -Recurse -ErrorAction Stop)
```
I would recommend using EA stop because the SilentlyContinue was hiding the real error.

Also because we no longer support PS2, can we change the `ModuleToProcess` in the manifest to `RootModule`?

**Comment by rkeithhill** [comment]
With the above fix, only two Pester tests fail on Linux:
```
    [-] dotNetCore1.1.0_should_pass 324ms
      Expected: {True}
      But was:  {False}
      52:             $psake.build_success | should -be $expectedResult
      at Invoke-Assertion, /home/hillr/.local/share/powershell/Modules/Pester/4.1.0/Functions/Assertions/Should.ps1: line 209
      at <ScriptBlock>, /mnt/c/Users/Keith/GitHub/psake/psake/tests/integration/spec.tests.ps1: line 52
    [-] dotNetCore2.0_should_pass 378ms
      Expected: {True}
      But was:  {False}
      52:             $psake.build_success | should -be $expectedResult
      at Invoke-Assertion, /home/hillr/.local/share/powershell/Modules/Pester/4.1.0/Functions/Assertions/Should.ps1: line 209
      at <ScriptBlock>, /mnt/c/Users/Keith/GitHub/psake/psake/tests/integration/spec.tests.ps1: line 52
```
This is probably something simple to figure out.

**Comment by rkeithhill** [comment]
This line in tasks.json isn't needed:
```
    "type": "process",
```
Each of the tasks is declaring its type as `shell`.

**Comment by rkeithhill** [comment]
OK latest changes are looking good on Linux.  Just those two test failures - and those are failing because I don't have dotnet installed in WSL.

**Comment by rkeithhill** [comment]
Installed dotnet, now all Pester tests pass on Linux.

**Comment by devblackops** [comment]
Awesome! I'm going to make your suggested changes re: `src` and create the `Build` task.

**Comment by rkeithhill** [comment]
This is looking good!  Can you add this to the settings.json file:
```
  "files.exclude": {
    "**/.git": true,
    "?.?.?/": true
  },
```
This will prevent workspace searches from find matches in the output folders.

**Comment by devblackops** [comment]
@rkeithhill Done.

**Comment by rkeithhill** [comment]
Do you want to bump the PSD1 version number in this PR to `4.7.0` or are you waiting to do that in a separate `prep-release` PR?   Other than that, this PR is looking good!

**Comment by devblackops** [comment]
I'll do another PR with the version bump and the final changes to the changelog.

**Pull request merged**
