### PR TITLE
Update init.ps1

### PR DESCRIPTION
**Pull request by jjrdk**
Removed unnecessary write to console.

### CODE REVIEW

**Comment by damianh** [comment]
This was happening in Visual Studio package manager console, mildly annoying. Cheers.

**Comment by damianh** [comment]
Er finally shipped.

**Comment by damianh** [comment]
I'm not even meant to be maintaining this.

Maybe .net 4.6 will be the last round. 

We should be using xplat tools for dnx stuff really.

**Comment by gep13** [comment]
>@damianh said...
We should be using xplat tools for dnx stuff really.

What are you planning on using?  (Just being nosey :-))

**Comment by damianh** [comment]
Not fully decided yet but am leaning towards something csx based. Though I'll take a look at fake too.

Whatever it is, it needs to be fully bootstrappable from the command line with nothing installed on server except `curl`, `wget` or similar and be fully xplat.

**Comment by gep13** [comment]
Thanks! I have been a long term psake user, but like you, am drawn to a more xplat build system.  I have been pointed at Bau and PVC: https://twitter.com/scriptcsnet/status/599145050111639552 and it looks like Cake will be xplat in the future, so looks like there are lots of options :-)

**Comment by damianh** [comment]
I was hoping for a xplat bootstrappable portable powershell, but don't
expect it to happen now.

**Comment by gep13** [comment]
Yeah, I think that would be stretch, although, who knows what Snover has got up his sleeves :-)

**Pull request merged**
